# Copyright © 2025 Algorivm

name: Build and test

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ homepage ]
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 'latest'

      - name: Install dependencies
        id: install
        run: yarn

      - name: Build
        id: build
        run: yarn build

      - name: Was the latest docs dist folder committed
        id: check-docs
        run: |
          # The user should have checked a docs folder in the commit
          # If the docs folder was updated, we will exit with an error
          # Because it means the docs folder checked in was not the latest
          
          # Perform a git diff to check if the dist folder was updated
          git diff --exit-code --quiet HEAD^ HEAD docs
          if [ $? -ne 0 ]; then
            echo "The docs folder was updated. Please commit the latest docs folder and then commit the changes."
            exit 1
          fi
